import type { NextPage } from 'next';
import Head from 'next/head';
import ConnectWalletWrapper from '../src/components/ConnectWalletWrapper/ConnectWalletWrapper';
import LensCreateProfile from '../src/components/LensCreateProfile/LensCreateProfile';
import LensLogin from '../src/components/LensLogin/LensLogin';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Kauri.io</h1>
        <ConnectWalletWrapper>
          {/* <Ping /> */}
          <LensLogin />
          <LensCreateProfile />
        </ConnectWalletWrapper>
      </main>
    </div>
  );
};

export default Home;
